/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedARouteRouteImport } from './routes/(authenticated)/a/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedASettingsIndexRouteImport } from './routes/(authenticated)/a/settings/index'
import { Route as authenticatedANotificationsIndexRouteImport } from './routes/(authenticated)/a/notifications/index'
import { Route as authenticatedAExploreIndexRouteImport } from './routes/(authenticated)/a/explore/index'
import { Route as authenticatedADashboardIndexRouteImport } from './routes/(authenticated)/a/dashboard/index'
import { Route as authenticatedASettingsProfileRouteImport } from './routes/(authenticated)/a/settings/profile'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/(auth-pages)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedARouteRoute = authenticatedARouteRouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedASettingsIndexRoute =
  authenticatedASettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedANotificationsIndexRoute =
  authenticatedANotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedAExploreIndexRoute =
  authenticatedAExploreIndexRouteImport.update({
    id: '/explore/',
    path: '/explore/',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedADashboardIndexRoute =
  authenticatedADashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)
const authenticatedASettingsProfileRoute =
  authenticatedASettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => authenticatedARouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a': typeof authenticatedARouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/a/settings/profile': typeof authenticatedASettingsProfileRoute
  '/a/dashboard': typeof authenticatedADashboardIndexRoute
  '/a/explore': typeof authenticatedAExploreIndexRoute
  '/a/notifications': typeof authenticatedANotificationsIndexRoute
  '/a/settings': typeof authenticatedASettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a': typeof authenticatedARouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/a/settings/profile': typeof authenticatedASettingsProfileRoute
  '/a/dashboard': typeof authenticatedADashboardIndexRoute
  '/a/explore': typeof authenticatedAExploreIndexRoute
  '/a/notifications': typeof authenticatedANotificationsIndexRoute
  '/a/settings': typeof authenticatedASettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/a': typeof authenticatedARouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(authenticated)/a/settings/profile': typeof authenticatedASettingsProfileRoute
  '/(authenticated)/a/dashboard/': typeof authenticatedADashboardIndexRoute
  '/(authenticated)/a/explore/': typeof authenticatedAExploreIndexRoute
  '/(authenticated)/a/notifications/': typeof authenticatedANotificationsIndexRoute
  '/(authenticated)/a/settings/': typeof authenticatedASettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a'
    | '/login'
    | '/api/auth/$'
    | '/a/settings/profile'
    | '/a/dashboard'
    | '/a/explore'
    | '/a/notifications'
    | '/a/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a'
    | '/login'
    | '/api/auth/$'
    | '/a/settings/profile'
    | '/a/dashboard'
    | '/a/explore'
    | '/a/notifications'
    | '/a/settings'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/(authenticated)/a'
    | '/(auth-pages)/login'
    | '/api/auth/$'
    | '/(authenticated)/a/settings/profile'
    | '/(authenticated)/a/dashboard/'
    | '/(authenticated)/a/explore/'
    | '/(authenticated)/a/notifications/'
    | '/(authenticated)/a/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  authPagesLoginRoute: typeof authPagesLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/a': {
      id: '/(authenticated)/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof authenticatedARouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/a/settings/': {
      id: '/(authenticated)/a/settings/'
      path: '/settings'
      fullPath: '/a/settings'
      preLoaderRoute: typeof authenticatedASettingsIndexRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/notifications/': {
      id: '/(authenticated)/a/notifications/'
      path: '/notifications'
      fullPath: '/a/notifications'
      preLoaderRoute: typeof authenticatedANotificationsIndexRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/explore/': {
      id: '/(authenticated)/a/explore/'
      path: '/explore'
      fullPath: '/a/explore'
      preLoaderRoute: typeof authenticatedAExploreIndexRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/dashboard/': {
      id: '/(authenticated)/a/dashboard/'
      path: '/dashboard'
      fullPath: '/a/dashboard'
      preLoaderRoute: typeof authenticatedADashboardIndexRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
    '/(authenticated)/a/settings/profile': {
      id: '/(authenticated)/a/settings/profile'
      path: '/settings/profile'
      fullPath: '/a/settings/profile'
      preLoaderRoute: typeof authenticatedASettingsProfileRouteImport
      parentRoute: typeof authenticatedARouteRoute
    }
  }
}

interface authenticatedARouteRouteChildren {
  authenticatedASettingsProfileRoute: typeof authenticatedASettingsProfileRoute
  authenticatedADashboardIndexRoute: typeof authenticatedADashboardIndexRoute
  authenticatedAExploreIndexRoute: typeof authenticatedAExploreIndexRoute
  authenticatedANotificationsIndexRoute: typeof authenticatedANotificationsIndexRoute
  authenticatedASettingsIndexRoute: typeof authenticatedASettingsIndexRoute
}

const authenticatedARouteRouteChildren: authenticatedARouteRouteChildren = {
  authenticatedASettingsProfileRoute: authenticatedASettingsProfileRoute,
  authenticatedADashboardIndexRoute: authenticatedADashboardIndexRoute,
  authenticatedAExploreIndexRoute: authenticatedAExploreIndexRoute,
  authenticatedANotificationsIndexRoute: authenticatedANotificationsIndexRoute,
  authenticatedASettingsIndexRoute: authenticatedASettingsIndexRoute,
}

const authenticatedARouteRouteWithChildren =
  authenticatedARouteRoute._addFileChildren(authenticatedARouteRouteChildren)

interface authenticatedRouteRouteChildren {
  authenticatedARouteRoute: typeof authenticatedARouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedARouteRoute: authenticatedARouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  authPagesLoginRoute: authPagesLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
